version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: astera-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - astera-data:/var/lib/postgresql/data
    ports:
      - "50432:${APP_DB_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    image: astera-backend:local
    container_name: astera-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      APP_DB_HOST: ${APP_DB_HOST}
      APP_DB_PORT: ${APP_DB_PORT}
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      SERVER_PORT: ${APP_SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${APP_SERVER_PORT}:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30

  frontend:
    image: astera-frontend:local
    container_name: astera-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "${NGINX_HTTP_PORT}:80"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost/ >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  astera-data:
