spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: astera-backend
  jackson:
    default-property-inclusion: non_null

app:
  company:
    name: "ООО «Астера»"
    phone: "+7 (495) 000-00-00"
    email: "sales@astera.example"
  pdf:
    title: "Подбор теплотехнического решения"
    logoPath: "static/logo.png"