server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: astera-backend
  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:astera}
    username: ${APP_DB_USER:astera}
    password: ${APP_DB_PASSWORD:pass123}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.springframework.security: INFO
    ru.astera.backend: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

app:
  jwt:
    secret: ${JWT_SECRET:dev-jwt-secret-key}
    expiration: 86400000 # 24 hours