server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: astera-backend
  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:heatdb}
    username: ${APP_DB_USER:heatuser}
    password: ${APP_DB_PASSWORD:heatpass}
  jpa:
    hibernate:
      ddl-auto: validate   # позже переключим на Flyway миграции
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info